version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: earthquake_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=earthquake_db
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-network

    command: sh -c "
      pnpm run migration:run &&
      pnpm run seed-csv &&
      pnpm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:4000/graphql
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: pnpm run dev

volumes:
  db_data:

networks:
  app-network:
